version: "3.8"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: app.Dockerfile
    image: laravel-image
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
#       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: >
      sh -c "ln -sf /var/www/storage/app/public /var/www/public/storage &&
             php artisan serve --host=0.0.0.0 --port=8000" 
    depends_on:
      - db
      - nginx
    networks:
      - app-network

  db:
    image: mysql:8.3
    platform: linux/x86_64
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    networks:
      - app-network
    

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge